Revert "不完善。"
Teahouse-Studios/mcwzh-meme-resourcepack pull request #184
Opened 2021-07-05 10:55 UTC by Dianliang233

@Ironnoob73 

# 提请合并

## 新增或更改的翻译

将“区块”改成“大块”
被岩浆块烫死的死亡信息改为“%1$s发现地板烫jo”
在火中死亡的死亡信息改为“%1$s被锟斤拷烫烫烫”
在岩浆中死亡的死亡信息改为“%1$s试图铁锅炖自己”
因火焰附加死亡的死亡信息改为“%1$s燃起来了！”
F3+H提示信息改为“F3 + H = 显示反食用过度框”
F3+G提示信息改为“F3 + G = 显示大块边界”
F3+D提示信息改为“F3 + D = 清空历史记录”
F3+F提示信息改为“F3 + F = 在目力程度间循环（按Shift来反向循环）”
无权限打开游戏模式切换器信息改为“你没有权限打开游戏模式切换器，爪巴！”
F3+A提示信息改为“F3 + A = 重新加载大块”
服务器关闭提示信息改为“拒绝访问”
服务器连接超时提示信息改为“太慢了！请不要尝试拿铁丝代替网线。”
服务器地址无效提示信息改为“404”
白色染料>稀饭（原一坨稀饭）

## 其它

添加精污花凋灵拓展包
添加垃圾分类拓展包

2021-07-05 10:56 UTC, Ironnoob73 commented
?

2021-07-05 11:05 UTC, Dianliang233 reviewed
@Ironnoob73

2021-07-05 11:05 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.clear_chat.help": "F3 + D = 清空历史记录",
为什么改成聊天记录？

2021-07-05 11:05 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "commands.forceload.added.failure": "没有被标记为强制加载的大块",
区块 => 大块的来源？

2021-07-05 11:05 UTC, Dianliang233 commented on modules/flowey_wither/module_manifest.json
> +    "description": "精污花凋灵",
恶心。

2021-07-05 11:05 UTC, Dianliang233 commented on modules/rubbish_sorting/module_manifest.json
> +    "description": "更改部分潜影盒",
贴图质量太差。

2021-07-05 11:06 UTC, XxLittleCxX requested changes
如 @Dianliang233

2021-07-05 11:22 UTC, Ironnoob73 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.advanced_tooltips.help": "F3 + H = 显示反食用过度框",
开启f3+h可以看到物品的注册名

2021-07-05 11:24 UTC, Ironnoob73 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.clear_chat.help": "F3 + D = 清空历史记录",
？
原文是聊天记录

2021-07-05 11:24 UTC, Ironnoob73 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "commands.forceload.added.failure": "没有被标记为强制加载的大块",
chunk通常翻译为大块

2021-07-05 11:26 UTC, Ironnoob73 commented on modules/flowey_wither/module_manifest.json
> +    "description": "精污花凋灵",
？

2021-07-05 11:26 UTC, Ironnoob73 commented on modules/flowey_wither/module_manifest.json
> +    "description": "精污花凋灵",
这个是传说之下的梗......

2021-07-05 11:30 UTC, Ironnoob73 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "disconnect.unknownHost": "404",
连接超时大多是由于数据传输过慢导致的；
寻不到网址的错误码是404，如果我没记错......

2021-07-05 11:31 UTC, XxLittleCxX commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "disconnect.unknownHost": "404",
http 上的 404 和 dns(或其他情况) 上的 unknown host 概念是不一样的

2021-07-05 11:45 UTC, Ironnoob73 commented
在提交更改的时候遇到问题，我似乎没有更改的权限......

2021-07-05 11:47 UTC, XxLittleCxX commented
稍等

2021-07-05 11:51 UTC, Dianliang233 commented on modules/flowey_wither/module_manifest.json
> +    "description": "精污花凋灵",
不欢迎引人不适的内容。

2021-07-05 11:52 UTC, XxLittleCxX commented
再试试推送

2021-07-05 11:52 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.clear_chat.help": "F3 + D = 清空历史记录",
修正：历史记录

2021-07-05 11:53 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "disconnect.unknownHost": "404",
连接超时也不只是数据传输过慢。请勿以偏概全。

2021-07-05 11:54 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.advanced_tooltips.help": "F3 + H = 显示反食用过度框",
那为什么又是“反食用过度”？

2021-07-05 11:57 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "disconnect.closed": "想进服？没门！",
还是不准确。

2021-07-05 11:58 UTC, Ironnoob73 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.advanced_tooltips.help": "F3 + H = 显示反食用过度框",
因为这样可以选择性地忽略掉更改的翻译（防止上头，在仓库ReadMe里写过，尽管和译名标准化根本上天差地别但也有一定作用）。

2021-07-05 11:59 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.advanced_tooltips.help": "F3 + H = 显示反食用过度框",
反直觉。请去除。

2021-07-05 12:03 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.advanced_tooltips.help": "F3 + H = 显示反食用过度框",
已回退。

2021-07-05 12:03 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "disconnect.unknownHost": "404",
已回退。

2021-07-05 12:04 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "commands.forceload.added.failure": "没有被标记为强制加载的大块",
请求 review @Teahouse-Studios/memified-chinese-content-group

2021-07-05 12:04 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "disconnect.closed": "想进服？没门！",
已回退。

2021-07-05 12:18 UTC, Ironnoob73 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.clear_chat.help": "F3 + D = 清空历史记录",
1.聊天栏不只有聊天，还有调试信息，死亡信息等；
2.历史记录可以影射的东西很多，比如你去的网站等。

2021-07-05 12:30 UTC, Dianliang233 commented on meme_resourcepack/assets/minecraft/lang/zh_meme.json
> +    "debug.clear_chat.help": "F3 + D = 清空历史记录",
1. 无论聊天栏用途再多，它还是聊天栏。
2. 正因历史记录可以影射的东西太多了，它才不应该被采用。

2021-07-06 07:05 UTC, XxLittleCxX approved these changes

2021-07-06 07:39 UTC, Neubulae approved these changes
可

2021-07-06 07:40 UTC, merged