:sparkles: add contents in #181
Teahouse-Studios/mcwzh-meme-resourcepack pull request #185
Opened 2021-07-06 07:49 UTC by XxLittleCxX

2021-07-06 08:08 UTC, Neubulae commented
wtf

2021-07-06 14:27 UTC, Dianliang233 requested changes
另外，请移除和原版一致的词条。

2021-07-06 14:29 UTC, Dianliang233 commented on modules/lang_mcbbs/module_manifest.json
> +    "name": "Mcbbs",
模块名称请保持与文件夹名一致。

2021-07-06 14:29 UTC, Dianliang233 commented on modules/lang_mcbbs/add.json
> +    "selectWorld.world": "茶馆"
我现在接受了。

2021-07-06 14:29 UTC, XxLittleCxX commented on modules/lang_mcbbs/module_manifest.json
> +    "name": "Mcbbs",
别骂了 这个json是我写的（

2021-07-06 14:30 UTC, Dianliang233 commented on modules/lang_mcbbs/module_manifest.json
> +    "name": "Mcbbs",
不应该作为 lang 模块。

2021-07-06 14:31 UTC, XxLittleCxX commented on modules/lang_mcbbs/module_manifest.json
> +    "name": "Mcbbs",
烦请你改

2021-07-07 02:51 UTC, SNWCreations commented
我很高兴我的这个作品被加入，也许此项目会被重启（当然还是以此资源包的模块形式更新）
看我有没有时间qwq

2021-07-09 03:58 UTC, Dianliang233 approved these changes
通过。

2021-07-09 03:58 UTC, merged